version: '3.8'

services:
  biometric-bridge:
    build:
      context: .
      dockerfile: Dockerfile
    image: auren-biometric-bridge:production
    container_name: biometric-bridge
    restart: unless-stopped
    ports:
      - "8889:8889"
    networks:
      - auren-network
    environment:
      # Core Infrastructure
      - REDIS_URL=redis://auren-redis:6379
      - POSTGRES_URL=postgresql://auren_user:auren_secure_2025@auren-postgres:5432/auren_production
      - KAFKA_BOOTSTRAP_SERVERS=auren-kafka:9092
      
      # Terra Integration (update when credentials are available)
      - TERRA_DEV_ID=pending
      - TERRA_API_KEY=pending
      - TERRA_WEBHOOK_SECRET=pending
      
      # Wearable APIs (for future direct integrations)
      - OURA_ACCESS_TOKEN=pending
      - WHOOP_CLIENT_ID=pending
      - WHOOP_CLIENT_SECRET=pending
      - WHOOP_WEBHOOK_SECRET=pending
      - OURA_WEBHOOK_SECRET=pending
      
      # Service Configuration
      - SERVICE_NAME=biometric-bridge
      - LOG_LEVEL=INFO
      - WORKERS=1
      - PORT=8889
      
      # CORS Configuration
      - CORS_ORIGINS=["https://auren-omacln1ad-jason-madrugas-projects.vercel.app", "http://localhost:3000", "http://localhost:5173"]
      
      # Additional Settings
      - MAX_CONCURRENT_WEBHOOKS=50
      - REDIS_TTL_SECONDS=86400
      - MAX_TIMESERIES_ENTRIES=10000
      - HEALTHKIT_ENABLED=true
      - PG_POOL_MIN_SIZE=5
      - PG_POOL_MAX_SIZE=20
      - AIOHTTP_CONNECTOR_LIMIT=100
      - OAUTH_LOCK_TTL_SECONDS=20
    
    volumes:
      - ./logs:/app/logs
    
    depends_on:
      - auren-redis
      - auren-postgres
      - auren-kafka
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8889/health"]
      interval: 30s
      timeout: 10s
      start_period: 40s
      retries: 3

networks:
  auren-network:
    external: true

# Note: This docker-compose.yml assumes the auren-network and infrastructure 
# containers (auren-redis, auren-postgres, auren-kafka) already exist.
# 
# To deploy:
# docker-compose up -d
#
# To view logs:
# docker-compose logs -f biometric-bridge
#
# To stop:
# docker-compose down 