version: '3.8'

services:
  tempo:
    image: grafana/tempo:2.4
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo-config.yaml:/etc/tempo.yaml
      - tempo-data:/var/tempo
    ports:
      - "3200:3200"   # Tempo API
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
    networks:
      - auren-network
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M
    environment:
      - TEMPO_STORAGE_TRACE_BACKEND=local
      - TEMPO_STORAGE_TRACE_LOCAL_PATH=/var/tempo
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3200/ready"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # Enhanced OTel Collector with Tempo exporter
  otel-collector-tempo:
    image: otel/opentelemetry-collector-contrib:0.95.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-tempo.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4319:4318"   # Alternative OTLP HTTP port
      - "9465:9464"   # Alternative Prometheus port
    networks:
      - auren-network
    depends_on:
      - tempo
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 256M
    environment:
      - OTEL_TRACES_SAMPLER=parentbased_traceidratio
      - OTEL_TRACES_SAMPLER_ARG=0.1  # 10% sampling
    restart: unless-stopped

volumes:
  tempo-data:

networks:
  auren-network:
    external: true 