version: '3.8'
services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - neuros_network
    
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=postgres
      - POSTGRES_DB=neuros
    ports:
      - "5432:5432"
    networks:
      - neuros_network
      
  # Add Kafka for biometric events
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - neuros_network
      
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - neuros_network
    
  neuros:
    build: .
    container_name: neuros
    depends_on:
      - redis
      - postgres
      - kafka
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URI=postgresql://postgres:example@postgres:5432/neuros
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NEUROS_ENV=development
    ports:
      - "8000:8000"
    networks:
      - neuros_network
    volumes:
      - ./config:/app/config  # Mount config directory for YAML files

networks:
  neuros_network: 