#!/bin/bash

echo "📋 Manual Deployment Steps for Enhanced Dashboard"
echo "================================================"
echo ""
echo "The enhanced dashboard has been built with new features!"
echo ""
echo "File locations:"
echo "- Local build: auren/dashboard_v2/dist/"
echo "- New JS file: index-CcacAJiZ.js (with enhancements)"
echo "- Old JS file: index-CTZOFJoO.js (current version)"
echo ""
echo "To deploy manually:"
echo ""
echo "1. Upload the package (already in progress):"
echo "   scp enhanced-dashboard.tar.gz root@144.126.215.218:/root/"
echo "   Password: .HvddX+@6dArsKd"
echo ""
echo "2. SSH into the server:"
echo "   ssh root@144.126.215.218"
echo "   Password: .HvddX+@6dArsKd"
echo ""
echo "3. Run these commands on the server:"
echo "   cd /root/auren-production"
echo "   tar -xzf /root/enhanced-dashboard.tar.gz -C auren/dashboard_v2/"
echo "   docker-compose -f docker-compose.prod.yml stop nginx"
echo "   docker-compose -f docker-compose.prod.yml start nginx"
echo ""
echo "4. Verify deployment:"
echo "   curl -s http://localhost | grep 'index-CcacAJiZ.js'"
echo ""
echo "5. Clear your browser cache and visit http://aupex.ai"
echo ""
echo "The new features include:"
echo "✨ Glassmorphism effects"
echo "✨ Neural particle background"
echo "✨ Enhanced animations"
echo "✨ Space-themed design"
echo "✨ Improved performance" 