version: '3.8'

services:
  biometric-bridge:
    build: .
    ports:
      - "8000:8000"
      - "9000:9000"  # Prometheus metrics
    environment:
      - POSTGRES_URL=postgresql://auren:password@postgres:5432/auren
      - REDIS_URL=redis://redis:6379/0
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
      - kafka
    networks:
      - auren-network

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: auren
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auren
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    ports:
      - "5432:5432"
    networks:
      - auren-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - auren-network

  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    networks:
      - auren-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - auren-network

volumes:
  postgres-data:

networks:
  auren-network:
    driver: bridge
