global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'neuros-blue'
    static_configs:
      - targets: ['neuros-blue:8001']
