# Tempo Configuration for AUREN Distributed Tracing
server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

ingester:
  max_block_duration: 5m

compactor:
  compaction:
    block_retention: 48h

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/blocks
    wal:
      path: /tmp/tempo/wal

querier:
  frontend_worker:
    frontend_address: 127.0.0.1:9095

overrides:
  defaults:
    metrics_generator:
      processors: [service-graphs, span-metrics]
      storage:
        path: /tmp/tempo/generator/storage
        remote_write:
          - url: http://auren-prometheus:9090/api/v1/write
            send_native_histograms: true

metrics_generator:
  registry:
    external_labels:
      source: tempo
      cluster: auren
  storage:
    path: /tmp/tempo/generator/wal
    remote_write:
      - url: http://auren-prometheus:9090/api/v1/write
        send_native_histograms: true
  processor:
    service_graphs:
      histogram_buckets: [0.1, 0.2, 0.4, 0.8, 1.6, 3.2, 6.4, 12.8]
    span_metrics:
      histogram_buckets: [0.002, 0.004, 0.008, 0.016, 0.032, 0.064, 0.128, 0.256, 0.512, 1.024, 2.048, 4.096, 8.192, 16.384]